# Generated by Django 3.1.1 on 2020-12-29 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=50)),
                ('Departament', models.CharField(max_length=40)),
                ('Estado', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=40)),
                ('Estado', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apellidos', models.CharField(max_length=40)),
                ('Nombres', models.CharField(max_length=40)),
                ('DNI', models.CharField(max_length=10)),
                ('Direccion', models.CharField(max_length=45)),
                ('Distrito', models.CharField(max_length=40)),
                ('Provincia', models.CharField(max_length=30)),
                ('Telefono', models.CharField(max_length=9)),
                ('Correo', models.CharField(max_length=40)),
                ('Estado', models.CharField(max_length=1)),
                ('cargos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movil.cargo')),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movil.categoria')),
            ],
        ),
    ]
