# Generated by Django 3.1.6 on 2021-05-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='Estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='Estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='Estado',
            field=models.IntegerField(default=1),
        ),
    ]
