# Generated by Django 3.1.6 on 2021-05-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movil', '0002_auto_20210530_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleparte',
            name='Cantidad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='marca',
            name='Estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='operciones',
            name='horas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='partehoras',
            name='TotalHoras',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='Estado',
            field=models.IntegerField(default=1),
        ),
    ]
