# Generated by Django 3.2 on 2021-06-05 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movil', '0003_auto_20210530_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['Desc_equipo'], 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ['Desc_marca'], 'verbose_name_plural': 'Marcas'},
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=30)),
                ('Clave', models.CharField(max_length=30)),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movil.empleado')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'ordering': ['Usuario'],
            },
        ),
    ]
