# Generated by Django 3.1.6 on 2021-06-05 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movil', '0004_auto_20210604_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'ordering': ['Orden'], 'verbose_name_plural': 'Ordenes'},
        ),
    ]
