# Generated by Django 3.1.6 on 2021-06-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movil', '0005_auto_20210605_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partehoras',
            options={'ordering': ['fecha'], 'verbose_name_plural': 'ParteHoras'},
        ),
        migrations.AddField(
            model_name='detalleparte',
            name='desc_actividad',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
