# Generated by Django 3.1.6 on 2021-06-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movil', '0008_auto_20210615_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleparte',
            options={'ordering': ['operacion'], 'verbose_name_plural': 'DetallePartes'},
        ),
        migrations.AddField(
            model_name='detalleparte',
            name='equipo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
