# Generated by Django 3.1.6 on 2021-06-19 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movil', '0009_auto_20210618_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleparte',
            old_name='NumParte',
            new_name='parte',
        ),
        migrations.AlterField(
            model_name='detalleparte',
            name='operacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='partehoras',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
