# Generated by Django 3.1.6 on 2021-06-19 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movil', '0010_auto_20210618_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partehoras',
            options={'ordering': ['id'], 'verbose_name_plural': 'ParteHoras'},
        ),
    ]
