# Generated by Django 3.1.6 on 2021-06-19 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movil', '0012_auto_20210619_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detparte',
            name='equipo',
        ),
    ]
