# Generated by Django 3.1.6 on 2021-07-09 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movil', '0013_remove_detparte_equipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detparte',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de parte', 'verbose_name_plural': 'Detalle de partes'},
        ),
        migrations.AlterModelOptions(
            name='partehoras',
            options={'ordering': ['id'], 'verbose_name': 'ParteHora', 'verbose_name_plural': 'ParteHoras'},
        ),
    ]
